# TCL File Generated by Component Editor 13.0sp1
# Thu Nov 20 20:55:59 CET 2025
# DO NOT MODIFY


# 
# MAC_FILTRE_INTERFACE "MAC_FILTRE_INTERFACE" v1.0
#  2025.11.20.20:55:59
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module MAC_FILTRE_INTERFACE
# 
set_module_property DESCRIPTION ""
set_module_property NAME MAC_FILTRE_INTERFACE
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "My Own IP Cores"
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME MAC_FILTRE_INTERFACE
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL MAC_FILTRE_INTERFACE
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file MAC_FILTRE_INTERFACE.vhd VHDL PATH ../src/MAC_FILTRE_INTERFACE.vhd TOP_LEVEL_FILE
add_fileset_file ADDC1.vhd VHDL PATH ../src/ADDC1.vhd
add_fileset_file ADDCN.vhd VHDL PATH ../src/ADDCN.vhd
add_fileset_file FILTRE_MOYENNEUR.vhd VHDL PATH ../src/FILTRE_MOYENNEUR.vhd
add_fileset_file MAC_OP.vhd VHDL PATH ../src/MAC_OP.vhd
add_fileset_file multiplier.vhd VHDL PATH ../src/multiplier.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point nios_custom_instruction_slave
# 
add_interface nios_custom_instruction_slave nios_custom_instruction end
set_interface_property nios_custom_instruction_slave clockCycle 0
set_interface_property nios_custom_instruction_slave operands 2
set_interface_property nios_custom_instruction_slave ENABLED true
set_interface_property nios_custom_instruction_slave EXPORT_OF ""
set_interface_property nios_custom_instruction_slave PORT_NAME_MAP ""
set_interface_property nios_custom_instruction_slave SVD_ADDRESS_GROUP ""

add_interface_port nios_custom_instruction_slave dataa dataa Input 32
add_interface_port nios_custom_instruction_slave datab b Input 32
add_interface_port nios_custom_instruction_slave n n Input 8
add_interface_port nios_custom_instruction_slave result result Output 32
add_interface_port nios_custom_instruction_slave clk_en clk_en Input 1
add_interface_port nios_custom_instruction_slave start start Input 1
add_interface_port nios_custom_instruction_slave done done Output 1

